### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by gemini-erin-monaco** [cvexaphp/namesApi#1]
I would like to utilize the data provided in Names1.json and Names2.json but you have not included any type of usage or license information. Please let me know what usage or licensing terms are acceptable for this project.

**Comment by cvexaphp** [comment]
Hello, the data is generated by this website : https://json-generator.com/
so if you want to use the data, check the website, if you ask me, I'm ok to use the code or the data as you wish  :)

**Comment by gemini-erin-monaco** [comment]
Hello,

  Thanks for the response, the info on json-generator.com, and the
permission. I ended up using copilot and gemini AI with public census data
like first and last names, street and city names, etc. and created my own
simple JSON arrays- I'm also working on a C# app to generate random
name/address, etc. records for a prototype project I'm working on to
showcase my skill. This includes things like fake "signature" capture
[generation] and so forth. I plan on setting up a github project to open
source the random record generator and public domain data files. Thank you,
and have a great day!
